V12 + Nginx
Yenthe666/InstallScript pull request #119
Opened 2018-10-04 07:29 UTC by tonybenoy

2018-10-10 18:13 UTC, Yenthe666 requested changes

2018-10-10 18:13 UTC, Yenthe666 commented on odoo_install.sh
> +  cat <<EOF > ~/odoo
Why not use our variable `OE_USER` here?

2018-10-10 18:13 UTC, Yenthe666 commented on odoo_install.sh
> +   access_log  /var/log/nginx/odoo-access.log;
Why not use our variable `OE_USER` here?

2018-10-10 18:13 UTC, Yenthe666 commented on odoo_install.sh
> +   error_log       /var/log/nginx/odoo-error.log;
Why not use our variable `OE_USER` here?

2018-10-10 18:13 UTC, Yenthe666 commented on odoo_install.sh
> +  sudo mv ~/odoo /etc/nginx/sites-available/
Not sure but do we really need `sudo` for all these operations?

2018-10-10 18:13 UTC, Yenthe666 commented on odoo_install.sh
> + echo "Done! The Nginx server is up and running. Configuration can be found at /etc/nginx/sites-available/odoo"
Why not use our variable `OE_USER` here?

2018-10-10 18:13 UTC, Yenthe666 commented on odoo_install.sh
> +sudo apt-get install python3 python3-pip -y
👍 good.

2018-10-10 18:25 UTC, tonybenoy commented
Thanks for the changes @Yenthe666 . I'll  test them out and get back to you :+1:

2018-10-10 18:29 UTC, Yenthe666 requested changes

2018-10-10 18:29 UTC, Yenthe666 commented on odoo_install.sh
> +  mv ~/odoo /etc/nginx/sites-available/
We should use `$OE_USER` for these too I believe.

2018-10-10 18:29 UTC, Yenthe666 commented on odoo_install.sh
> +  ln -s /etc/nginx/sites-available/odoo /etc/nginx/sites-enabled/odoo
We should use `$OE_USER` for these too I believe.

2018-10-10 18:29 UTC, Yenthe666 commented
@tonybenoy I think we need those too. It looks neat :)

2018-10-10 18:46 UTC, Yenthe666 requested changes

2018-10-10 18:46 UTC, Yenthe666 commented on odoo_install.sh
> +  ln -s /etc/nginx/sites-available/odoo /etc/nginx/sites-enabled/$OE_USER
Shouldn't you change the first part too? It now has /odoo hardcoded.

2018-10-10 18:47 UTC, Yenthe666 commented
@tonybenoy can you solve that final one & rebase? I made some commits with other improvements and fixes that give issues now.
Can you give it one more test run locally maybe?

2018-10-26 06:59 UTC, tonybenoy commented
Hey @Yenthe666 . Sorry for not responding. I was not available for the time. I'm trying to make some time to make all the changes that you suggested. I did try with the minor name changes and got some issues. So I'll do some more proper testing and get back to you :)

2018-12-27 14:44 UTC, Yenthe666 commented
Let us close this one off in favour of https://github.com/Yenthe666/InstallScript/pull/137

2018-12-27 14:44 UTC, closed without merging